### Test route
GET http://localhost:4673/v1/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDcxMjU4ODAsImV4cCI6MTcwNzEyNTg5NSwiYXVkIjoidGVzdDVAdGVzdDIuY29tIiwiaXNzIjoiaHR0cHM6Ly9kYW1lbmdyYW5kb20udmVyY2VsLmFwcCJ9.4BuxzWKU8I4TzJxEuD18_mXq7zydSuh_G5QBtsEcbHQ

### Failure case

GET http://localhost:4673/v1/test_failed

### register route

POST http://localhost:4673/v1/auth/register
Content-Type: application/json

{
  "email": "test9@test3.com",
  "password": "test123"
}

### login route

POST http://localhost:4673/v1/auth/login
Content-Type: application/json

{
  "email": "test5@test2.com",
  "password": "test123"
}


### refresh token route

POST http://localhost:4673/v1/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDcxMjU4NTEsImV4cCI6MTczODY4MzQ1MSwiYXVkIjoidGVzdDVAdGVzdDIuY29tIiwiaXNzIjoiaHR0cHM6Ly9kYW1lbmdyYW5kb20udmVyY2VsLmFwcCJ9.a8rvtj1WsBrWToFBFiEiqpJdweig3JHM3bY-dFq-ED0"
}

### logout route

DELETE http://localhost:4673/v1/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDcxMjU5MDMsImV4cCI6MTczODY4MzUwMywiYXVkIjoidGVzdDVAdGVzdDIuY29tIiwiaXNzIjoiaHR0cHM6Ly9kYW1lbmdyYW5kb20udmVyY2VsLmFwcCJ9.ElKxpPwwdwFPytKCmzqpB4s2uYYjWwfOdDOiRh-SRmA"
}

# redis-commander: use for redis way to save and verify JWT token
# redis-cli: you can try locally how to use redis in lcoal environment
